version: "3.1"
services:

  broadcast_api:
    container_name: broadcast_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/src
    ports:
      - "9999:9999"

  nginx:
    image: nginx
    container_name: nginx-broadcast
    volumes:
    # Nginx configs
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
    - "80:80"
    - "8080:8080"
    - "443:443"
    depends_on:
      - broadcast_api

  dozzle:
    container_name: broadcast-dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8888:8080

  logseq:
    image: "ghcr.io/logseq/logseq-webapp:latest"
    ports:
      - 3001:80